# Generated by Django 5.2.17 on 2026-09-08 14:36

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationDimension",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("key", models.SlugField(max_length=100)),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="dimensions",
                        to="annotations.project",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.CreateModel(
            name="ProjectTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("configuration", models.JSONField(blank=True, default=dict)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["key", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("key", "version"), name="unique_template_key_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="template_version_at_least_one",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="project",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="annotations.projecttemplate",
            ),
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("subject_id", models.CharField(max_length=100)),
                ("name", models.CharField(blank=True, max_length=200)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subjects",
                        to="annotations.project",
                    ),
                ),
            ],
            options={
                "ordering": ["subject_id"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationLabel",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "color",
                    models.CharField(
                        default="#7056d3",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9a-fA-F]{6}$", "Use a six-digit hex color."
                            )
                        ],
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "dimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="labels",
                        to="annotations.annotationdimension",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dimension", "name"),
                        name="unique_label_name_per_dimension",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="annotationdimension",
            constraint=models.UniqueConstraint(
                fields=("project", "key"), name="unique_dimension_key_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="project",
            constraint=models.CheckConstraint(
                condition=models.Q(("status__in", ["draft", "active", "archived"])),
                name="project_status_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                fields=("project", "subject_id"), name="unique_subject_id_per_project"
            ),
        ),
    ]
