# Generated by Django 5.2.17 on 2026-09-15 14:14

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("annotations", "0002_usersecurity"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnnotationJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="annotation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_annotation_jobs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationWorkItem",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="work_items",
                        to="annotations.annotationjob",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnnotationResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "work_item",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="result",
                        to="annotations.annotationworkitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("key", models.SlugField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("instructions", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("ready", "Ready"),
                            ("in_progress", "In progress"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tasks",
                        to="annotations.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="annotationjob",
            name="task",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="annotations.task",
            ),
        ),
        migrations.CreateModel(
            name="TaskSubject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="task_subjects",
                        to="annotations.subject",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_subjects",
                        to="annotations.task",
                    ),
                ),
            ],
            options={
                "ordering": ["subject__subject_id"],
            },
        ),
        migrations.AddField(
            model_name="task",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="tasks",
                through="annotations.TaskSubject",
                to="annotations.subject",
            ),
        ),
        migrations.AddField(
            model_name="annotationworkitem",
            name="task_subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="work_items",
                to="annotations.tasksubject",
            ),
        ),
        migrations.CreateModel(
            name="VideoAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "source_type",
                    models.CharField(
                        choices=[("upload", "Local upload"), ("remote", "Remote URL")],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True, max_length=4096)),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("uploading", "Uploading"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("ready", "Ready"),
                            ("failed", "Failed"),
                        ],
                        default="uploading",
                        max_length=20,
                    ),
                ),
                (
                    "fps",
                    models.DecimalField(
                        blank=True, decimal_places=4, max_digits=10, null=True
                    ),
                ),
                ("frame_count", models.PositiveIntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_assets",
                        to="annotations.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VideoView",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("main", "Main"),
                            ("back", "Back"),
                            ("subject", "Subject"),
                        ],
                        max_length=20,
                    ),
                ),
                ("position", models.PositiveIntegerField(default=0)),
                (
                    "asset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="video_views",
                        to="annotations.videoasset",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_views",
                        to="annotations.subject",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="video_views",
                        to="annotations.task",
                    ),
                ),
            ],
            options={
                "ordering": ["position", "name"],
            },
        ),
        migrations.AddConstraint(
            model_name="annotationjob",
            constraint=models.UniqueConstraint(
                fields=("task", "assigned_to"), name="unique_job_per_task_annotator"
            ),
        ),
        migrations.AddConstraint(
            model_name="tasksubject",
            constraint=models.UniqueConstraint(
                fields=("task", "subject"), name="unique_subject_per_task"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.UniqueConstraint(
                fields=("project", "key"), name="unique_task_key_per_project"
            ),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "status__in",
                        ["draft", "ready", "in_progress", "completed", "archived"],
                    )
                ),
                name="task_status_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationworkitem",
            constraint=models.UniqueConstraint(
                fields=("job", "task_subject"), name="unique_work_item_per_job_subject"
            ),
        ),
        migrations.AddConstraint(
            model_name="annotationworkitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("status__in", ["assigned", "in_progress", "completed", "reviewed"])
                ),
                name="annotation_work_item_status_is_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "main")),
                fields=("task",),
                name="one_main_video_per_task",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "back")),
                fields=("task",),
                name="one_back_video_per_task",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoview",
            constraint=models.UniqueConstraint(
                condition=models.Q(("role", "subject")),
                fields=("task", "subject"),
                name="one_subject_video_per_task_subject",
            ),
        ),
        migrations.AddConstraint(
            model_name="videoview",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("role", "subject"), ("subject__isnull", False)),
                    models.Q(
                        models.Q(("role", "subject"), _negated=True),
                        ("subject__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="video_role_matches_subject",
            ),
        ),
    ]
