# Generated by Django 5.2.17 on 2026-09-18 23:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def classify_existing_templates(apps, schema_editor):
    template_model = apps.get_model("annotations", "ProjectTemplate")
    for project_type in ("cvip2020", "cvip2026"):
        template_model.objects.filter(key__iexact=project_type).update(
            project_type=project_type
        )


class Migration(migrations.Migration):
    dependencies = [
        (
            "annotations",
            "0003_annotationjob_annotationworkitem_annotationresult_and_more",
        ),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="projecttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="project_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="projecttemplate",
            name="project_type",
            field=models.CharField(
                choices=[
                    ("dipser", "DIPSER"),
                    ("cvip2020", "CVIP2020"),
                    ("cvip2026", "CVIP2026"),
                ],
                default="dipser",
                max_length=40,
            ),
        ),
        migrations.RunPython(classify_existing_templates, migrations.RunPython.noop),
    ]
